#!/opt/pwn.college/python
from os.path import exists

USERFILE = '/home/hacker/my_nano_file.txt'
USERTEXT = "When one does not love too much, one does not love enough."
HISTORY = '/home/hacker/.bash_history'

def main():

    if exists(USERFILE):
        with open(USERFILE, 'r') as fObj:
            data = fObj.read()
            if USERTEXT.lower() in data.lower():
                print("The file still contains the original text! Please change it!")
                exit(0)
            else:
                print(f"Good job! You changed the text to: '{data}'")
    else:
        print("Couldn't find 'my_nano_file.txt' in your home directory.")
        print("If you didn't do the previous challenge, go and do that now.")
        print("If you did do the previous challenge, then just re-create 'my_nano_file.txt'.")
        exit(0)
    

    with open(HISTORY, 'r') as fObj:
        for x in fObj.readlines():
            if 'nano' in x.split(' ')[0].strip():
                with open('/flag', 'r') as fObj2:
                    print(fObj2.read())
                    exit(0)

    print("It looks like you didn't use nano to do this challenge. Please use 'nano'.")


if __name__ == "__main__":
    main()

