#!/usr/bin/env python

import sys
from getpass import getpass

# Fake version of passwd

def write_success_file(password):
    with open("/tmp/.challenge_complete", "w") as f:
        f.write(password)


def main():
    if len(sys.argv) < 2 or sys.argv[1] != "wkiffin":
        print("passwd: please change the password of the wkiffin user like this: passwd wkiffin")
    else:
        password = getpass("New password: ")
        recheck = getpass("Retype new password: ")

        if password != recheck:
            print("Sorry, passwords do not match.")
            print("passwd: Authentication token manipulation error")
            print("passwd: password unchanged")
        else:
            write_success_file(password)
            print("passwd: password updated successfully")


if __name__ == "__main__":
    main()
