#!/opt/pwn.college/python
import random
from os import makedirs
from os import environ
from os import system
from os.path import join, exists

DATA_FILE = "/tmp/.user.data"

def setup_game():
    random_words = [
        "brisk", "jumpy", "zesty", "livid", "quirk", "mango", "fluff", "gleam", "bliss", "vivid",
        "prong", "crisp", "swoon", "pluck", "charm", "smirk", "witty", "glide", "sprig", "whirl",
        "buzzy", "clamp", "swift", "glee", "jolly", "flick", "brawn", "slink", "twist", "clink",
        "spark", "bloom", "frisk", "flair", "knack", "scamp", "quirk", "flash", "jumpy", "brine",
        "snare", "sweep", "frost", "shard", "prick", "flock", "grind", "creek", "gleam", "brisk",
        "pluck", "swoop", "snare", "clash", "slink", "blaze", "crisp", "flick", "glee", "tweak",
        "latch", "shirk", "blurb", "chirp", "whizz", "glint", "trill", "swoop", "quirk", "whisk",
        "gleam", "gruff", "spunk", "flair", "smirk", "brisk", "swift", "twirl", "grind", "brash",
        "slick", "gloss", "whirl", "fizz", "clink", "knack", "pluck", "snarl", "frizz", "whisk",
        "scuff", "twinge", "spurt", "chime", "bliss", "frisk", "twist", "smirk", "shard", "clamp"
    ]

    # Create random winning dir
    winning_dir = "/tmp/starthere"
    end = random.randint(2, 4)
    for x in range(0, end):
        winning_dir = join(winning_dir, random_words.pop(random.randrange(len(random_words))))
        

    makedirs(winning_dir)

    filename = f"find_me.txt"
    with open(join(winning_dir, filename), 'w') as fObj:
        fObj.write("If you found me, you win! Run `/challenge/solve` and enter my full file path when it asks!")

    with open(DATA_FILE, 'w') as fObj:
        fObj.write(join(winning_dir, filename))

    

def main():
    # Set up challenge
    # Create a bunch of dirs that they need to traverse through to find 
    # a file that has a specific name which they will need to supply 
    # to get the flag
    if not exists(DATA_FILE):
        print("Setting up challenge...")
        setup_game()
        print("""
        Sometimes when you're using a computer you
        need to find a file, but you can't remember
        where it is.

        In Windows, you can open the file explorer
        and search for the particular file you want.
        In the terminal, you can do a similar thing!

        Using the 'find' command, you can give it
        specific information about a file, and it will
        show you where it is located on your system.

        The syntax for the find command will look like
        this:

        'find / -name {filename}'
         
            - 'find' is us invoking the command.
            - '/' is the directory we want to search in.
              In this case '/' means 'search the whole
              system'
            - '-name {filename}' is the name of the file
              we want to find.

        Given this information, search the '/tmp/starthere'
        directory for a file named 'find_me.txt'.

        Then copy the output that find gives you and run
        '/challenge/solve' and supply that to get the 
        flag!

        Good luck!

        """)
    else:
        print("Hopefully you found the file!")
        ans = input("Please give me the full path: ")
        if '/tmp/starthere' in ans and exists(ans.strip()):
            print("Correct! Here is your flag!")
            with open("/flag", 'r') as fObj:
                print(fObj.read())
                return
        else:
            print("Not quite! Try again!")
            return


if __name__ == "__main__":
    main()

